= Contributors =

Original code (pre-library): https://github.com/NicoHood/HID[NicoHood/HID]

* Links/Credits

** http://www.fourwalledcubicle.com/LUFA.php[LUFA from Dean Camera]

** https://github.com/harlequin-tech/arduino-usb[Darran's HID Projects]

** http://www.imaginaryindustries.com/blog/?p=80[Connor's Joystick for the Leonardo]

** http://stefanjones.ca/blog/arduino-leonardo-remote-multimedia-keys/[Stefan Jones Multimedia Keys Example]

** https://github.com/aduitsis/ardumultimedia[Athanasios Douitsis Multimedia Keys Example]

** https://github.com/arduino/ArduinoCore-avr/tree/master/firmwares/atmegaxxu2/arduino-usbserial[The Original Arduino Sources]

** http://www.usblyzer.com/[USBlyzer]

** https://www.mattairtech.com/index.php/old-products/mt-db-u1.html[Mattairtechs 16u2 Lufa USB Core]

** https://github.com/pbrook/minimus-arduino[Paul Brook's Minimus 32u2 Arduino USB Core]

** https://github.com/PaulStoffregen/cores[Paul Stoffregen's Teensy Core]

** http://forum.arduino.cc/index.php?topic=173583.0[Keyboard Led Out report by hartmut_holgraefe]

** https://github.com/arduino/Arduino/pull/1803[Github Pull Request with a lot of new functions]

** https://petervanhoyweghen.wordpress.com/2012/09/16/arduinoisp-on-the-leonardo/[Arduino ISP fix]

** A lot of searching through the web

** The awesome official Arduino IRC chat!

** https://github.com/NicoHood/NicoHoodProtocol[The NicoHood Protocol]

** See HoodLoader1&2 repository for more credits/links

See https://github.com/NicoHood/HID/wiki/Useful-Links-Credits[NicoHood/HID/wiki/Useful-Links-Credits] for the whole information.

* Contributor

** https://github.com/MRNIU[MRNIU]

== License ==

Copyright (c) 2014-2015 NicoHood

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
